#######################################################################################
# Book settings
title: Zpracování dat pro ZFM a PRAK
author: Adam Červenka a Štěpán Skalka
email: ''
logo                        : "assets/icon2.png"  # A path to the book logo
exclude_patterns            : ["README.md"]  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : 'off'  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  timeout                   : 600    # The maximum time (in seconds) each notebook cell is allowed to run.

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "assets/icon1.png"  # A path to a favicon image
  navbar_number_sections    : True  # Add a number to each section in your left navbar
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  use_repository_button     : true
  use_edit_page_button      : false
  use_issues_button         : false

sphinx:
  extra_extensions: [sphinxcontrib.youtube]

#######################################################################################
# Launch button settings
launch_buttons:
  jupyterhub_url            : https://jupyter.fjfi.cvut.cz/
  notebook_interface        : jupyterlab

repository:
  url                       : https://github.com/TheLittleRock/ZFManual # The URL to your book's repository
  branch                    : main  # Which branch of the repository should be used when creating links